MailQueue:
  Type: AWS::SQS::sqsQueue
  Properties:
    QueueName: ${self:custom.mailQueue.name}

Outputs:
  MailQueueArn:
    Value: ${self:custom.mailQueue.arn}
    Export:
      Name: ${self:custom.mailQueue.arn}-Arn
  MailQueueUrl:
    Value: ${self:custom.mailQueue.url}
    Export:
      Name: ${self:custom.mailQueue.arn}-Url